alias ll='ls -lah'
alias cat='batcat'
alias vim='nvim'
alias brightness='xrandr --output eDP-1 --brightness'
alias info='info --vi-keys'
alias fsi='dotnet fsi -r ~/.local/bin/fsharp/FsLexYacc.Runtime.dll'
