# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=20000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
if [ -d "${CONFIG_HOME}/terminalenv/bash" ]; then
  export TERMENV="${TERMENV:-${CONFIG_HOME}/terminalenv}"
  HERE="${TERMENV}/bash"
else
  SOURCE_PATH="${BASH_SOURCE[0]}"
  while [ -L "$SOURCE_PATH" ]; do
      SOURCE_DIR="$(cd -P "$(dirname "$SOURCE_PATH")" >/dev/null 2>&1 && pwd)"
      SOURCE_PATH="$(readlink "$SOURCE_PATH")"
      if [[ "$SOURCE_PATH" != /* ]]; then
          SOURCE_PATH="$SOURCE_DIR/$SOURCE_PATH"
      fi
  done
  HERE="$(cd -P "$(dirname "$SOURCE_PATH")" >/dev/null 2>&1 && pwd)"
  export TERMENV="${TERMENV:-$(dirname "$(dirname "$HERE")")}"
fi

if [ -f "${HERE}/completions/git" ]; then
  source "${HERE}/completions/git"
else
  echo "Warning: git completion not found at ${HERE}/completions/git" >&2
fi
export GIT_COMPLETION_CHECKOUT_NO_GUESS=1

source "${HERE}/lib.sh"
source "${HERE}/env.sh"
source "${HERE}/aliases.sh"
source "${HERE}/prompt.sh"
source "${HERE}/path.sh"
unset CONFIG_HOME HERE SOURCE_DIR SOURCE_PATH
