"$schema" = 'https://starship.rs/config-schema.json'

format = """$cmd_duration[---](bold) $directory\
$git_branch$git_commit$git_state$git_status\
$package\
$c\
$cmake\
$haskell\
$java\
$gradle\
$pulumi\
$python\
$rust\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$custom\
$sudo\
$jobs\
$status\
$container\
$netns $character"""

add_newline = false

[character]
success_symbol = '[»](bold purple)'
error_symbol = '[»](bold red)'

[cmd_duration]
format = "took [$duration]($style)\n"

[directory]
truncate_to_repo = false
style = 'bold bright-white'

[git_branch]
symbol = ''
style = 'yellow'
format = '[‹](yellow)[$symbol$branch(:$remote_branch)]($style)'

# mangler "dirty" (* i ohmyzsh), så "untracked" er ?).
# manger 
[git_status]
format = "$dirty$untracked$ahead_behind $index_added$index_modified$renamed$index_deleted$worktree_modified$worktree_deleted$worktree_added$conflicted$stashed[›](yellow)"
ahead = '[➔](blue)'
dirty = '[*](red)'
untracked = '[?](red)'
modified = '[M](red)'
staged = '[A](green)'
renamed = '[R](green)'
deleted = "[D](red)"
worktree_added = "[?](red)"
worktree_deleted = "[D](red)"
worktree_modified = "[M](red)"
index_added = "[A](green)"
index_deleted = "[D](green)"
index_modified = "[M](green)"

[line_break]
disabled = true
